// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iioyoibajvpzagospjzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3lvaWJhanZwemFnb3NwanpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTA3NzIsImV4cCI6MjA2Mzg2Njc3Mn0.qK8P5NkeGE628vE8NsgEywa8H_aoP2TI2RTUV_wBym4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);